changelog:
  categories:
    - title: 破壊的変更
      labels:
        - breaking

    - title: 新機能・改善
      labels:
        - feature
        - enhancement

    - title: 脆弱性対応
      labels:
        - security

    - title: バグ修正
      labels:
        - bug
        - fix

    - title: テスト・内部改善
      labels:
        - test
        - chore
        - ci
        - github_actions
        - refactor

    - title: その他
      labels:
        - "*"
